name: gideon_ogbonna_portfolio
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.0
  macos_ui: ^2.0.0
  responsive_sizer: ^3.2.0
  intl: ^0.18.1
  flutter_svg: ^2.0.7
  one_clock: ^1.0.9
  easy_localization: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/language/
    - assets/language/
    - assets/images/
    - assets/svg/
    - assets/
    # - images/a_dot_ham.jpeg

  fonts:
    - family: MacOSFont
      fonts:
        - asset: assets/fonts/SFPRODISPLAYBOLD.OTF
          weight: 700
        - asset: assets/fonts/SFPRODISPLAYMEDIUM.OTF
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF
          style: italic
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700